<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.8.25" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />


<title>Grease or Sand? Regulatory Quality as a Moderator of Corruption’s Effect on FDI in Africa – Razi Mrad - PSCI 3200</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<!-- htmldependencies:E3FAD763 -->
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  
  <script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>


<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="/index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="/index.html">
    <span class="navbar-title">Razi Mrad - PSCI 3200</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
  aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation"
  onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="/index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="/psci_final.html"> 
<span class="menu-text">Final Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <div id="quarto-toc-target"></div>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Grease or Sand? Regulatory Quality as a Moderator of Corruption’s Effect on FDI in Africa</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#theory-and-hypotheses" id="toc-theory-and-hypotheses"><span class="header-section-number">2</span> Theory and Hypotheses</a>
  <ul>
  <li><a href="#the-complementarity-mechanism" id="toc-the-complementarity-mechanism"><span class="header-section-number">2.1</span> The Complementarity Mechanism</a></li>
  <li><a href="#the-substitution-mechanism" id="toc-the-substitution-mechanism"><span class="header-section-number">2.2</span> The Substitution Mechanism</a></li>
  <li><a href="#falsifiability-and-placebo-testing" id="toc-falsifiability-and-placebo-testing"><span class="header-section-number">2.3</span> Falsifiability and Placebo Testing</a></li>
  </ul></li>
  <li><a href="#research-design" id="toc-research-design"><span class="header-section-number">3</span> Research Design</a>
  <ul>
  <li><a href="#data" id="toc-data"><span class="header-section-number">3.1</span> Data</a></li>
  <li><a href="#threats-to-inference" id="toc-threats-to-inference"><span class="header-section-number">3.2</span> Threats to Inference</a></li>
  </ul></li>
  <li><a href="#findings" id="toc-findings"><span class="header-section-number">4</span> Findings</a></li>
  <li><a href="#empirical-extension" id="toc-empirical-extension"><span class="header-section-number">5</span> Empirical Extension</a></li>
  <li><a href="#discussion-and-policy-implications" id="toc-discussion-and-policy-implications"><span class="header-section-number">6</span> Discussion and Policy Implications</a></li>
  <li><a href="#references" id="toc-references">References</a></li>
  </ul>
</nav>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1"><span class="header-section-number">1</span> Introduction</h2>
<p>Despite decades of policy reform, Africa attracts a disproportionately small share of global foreign direct investment (FDI). Inflows reached an estimated $59 billion in 2025, just over 3% of the global total for a continent accounting for roughly 18% of the world’s population <span class="citation" data-cites="unctad2026">(<a href="#ref-unctad2026" role="doc-biblioref">United Nations Conference on Trade and Development 2026</a>)</span>. While many factors contribute to this gap, understanding it requires grappling with a contested question at the heart of the institutional economics literature: does corruption inherently deter foreign investment, or can it sometimes facilitate it?</p>
<p>Historically, two mechanisms have pulled in opposite directions. The standard view treats corruption as a direct tax on investment: bribes and regulatory unpredictability raise effective entry costs, lower expected returns, and expose multinational firms to legal liability under home-country anti-bribery statutes. On this account, corruption should unambiguously reduce FDI, acting as “sand in the wheels” of the economy <span class="citation" data-cites="mauro1995 wei2000">(<a href="#ref-mauro1995" role="doc-biblioref">Mauro 1995</a>; <a href="#ref-wei2000" role="doc-biblioref">Wei 2000</a>)</span>. However, a competing perspective — the “grease the wheels” hypothesis — argues that in environments where formal institutions are highly dysfunctional, corruption can help investors navigate bureaucratic obstacles, secure permits, and enforce informal agreements that courts cannot enforce. Under this logic, corruption might attract FDI precisely where formal governance fails most <span class="citation" data-cites="quazi2014">(<a href="#ref-quazi2014" role="doc-biblioref">Quazi, Vemuri, and Soliman 2014</a>)</span>.</p>
<p>The empirical literature increasingly suggests that the resolution to this debate lies in the broader institutional context. The key contribution of <span class="citation" data-cites="meon2005">Méon and Sekkat (<a href="#ref-meon2005" role="doc-biblioref">2005</a>)</span> is to show that corruption’s effects are not constant but depend heavily on the quality of surrounding institutions. However, this conditional relationship presents a theoretical fork in the road, offering two mutually exclusive stories for how regulatory quality interacts with corruption.</p>
<p>The first story is complementarity: higher regulatory quality reduces the harmful effects of corruption on FDI. In this scenario, investors use bribes to efficiently bypass the remaining inefficiencies in an otherwise functioning system. The second story is substitution: higher regulatory quality makes corruption <em>more</em> harmful to FDI. If a country has clear, functioning, and transparent market rules, investors do not need to pay bribes to get things done. In this strong regulatory environment, the “greasing” benefit of corruption disappears, and it acts strictly as a punitive, unpredictable tax that drives investors away.</p>
<p>While both stories have theoretical backing in the literature, existing research has not fully resolved which mechanism dominates in the African context. For instance, <span class="citation" data-cites="benassy2007">Bénassy-Quéré, Coupet, and Mayer (<a href="#ref-benassy2007" role="doc-biblioref">2007</a>)</span> found in a broad cross-country study that regulatory quality outperforms control of corruption as a predictor of FDI globally, but they do not directly test the continuous interaction between the two. Directly relevant is <span class="citation" data-cites="lakha2024">Lakha et al. (<a href="#ref-lakha2024" role="doc-biblioref">2024</a>)</span>, who uses threshold regression across 34 African countries to show that corruption’s deterrent effect on FDI emerges once governance falls below certain thresholds. Yet Lakha et al. examine discrete regime changes rather than a continuous moderating relationship, and they do not explicitly pit the complementarity and substitution mechanisms against one another.</p>
<p>This project addresses that gap by asking: Does regulatory quality mitigate the deterrent effect of corruption on FDI in Africa (complementarity), or does it exacerbate it by rendering corruption an unnecessary tax (substitution)? To answer this, we use a comprehensive panel dataset of 54 African countries over the period 2005–2022, drawn from the World Bank’s World Development Indicators and Worldwide Governance Indicators. By employing a continuous interaction specification, this analysis does not pre-commit to a single theoretical outcome — it lets the data assess which mechanism dominates the realities of foreign investment in Africa. Understanding which mechanism is at play is critical not just for academic theory, but for policymakers attempting to sequence institutional reforms to attract global capital.</p>
</section>
<section id="theory-and-hypotheses" class="level2" data-number="2">
<h2 data-number="2"><span class="header-section-number">2</span> Theory and Hypotheses</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class='callout-icon'></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Note on variable coding:</strong> The WGI “Control of Corruption” index is scaled so that higher values indicate stronger control i.e., less corruption. Therefore, a positive baseline association means that reducing corruption increases FDI.</p>
</div>
</div>
<p>Foreign direct investment is a long-horizon commitment. Firms acquire assets, build supply chains, and hire local workforces in anticipation of returns that materialize over years or decades. Because of this long time-horizon, investors are acutely sensitive not only to the immediate prevalence of corruption, but to the broader institutional matrix in which that corruption occurs.</p>
<p>The existing literature presents a theoretical fork in the road regarding how regulatory quality conditions the impact of corruption on investment. Rather than pre-committing to a single outcome, this analysis sets up a direct test between two plausible yet mutually exclusive relationships.</p>
<section id="the-complementarity-mechanism" class="level3" data-number="2.1">
<h3 data-number="2.1"><span class="header-section-number">2.1</span> The Complementarity Mechanism</h3>
<p>The complementarity theory argues that good regulations and clean government amplify one another. Under this logic, formal market rules (regulatory quality) and the impartial enforcement of those rules (control of corruption) are both necessary to attract foreign capital.</p>
<p>If a country has high regulatory quality but officials remain highly corrupt, those excellent regulations are easily subverted by predatory bureaucrats. Conversely, if a government successfully eradicates corruption but leaves a paralyzing, dysfunctional regulatory framework in place, businesses will choke on the red tape because they can no longer bribe their way through it. Therefore, investors will only fully commit capital when both dimensions are strong. As <span class="citation" data-cites="meon2005">Méon and Sekkat (<a href="#ref-meon2005" role="doc-biblioref">2005</a>)</span> notes, institutional weaknesses compound.</p>
<p>If complementarity holds, the positive effect of controlling corruption on FDI will be magnified in environments with good regulations.</p>
<blockquote>
<p><strong>H1a (Complementarity):</strong> The positive association between corruption control and FDI inflows will be stronger in countries with higher regulatory quality, resulting in a positive interaction coefficient (<span class="math inline">\(\hat{\beta}_3 &gt; 0\)</span>).</p>
</blockquote>
</section>
<section id="the-substitution-mechanism" class="level3" data-number="2.2">
<h3 data-number="2.2"><span class="header-section-number">2.2</span> The Substitution Mechanism</h3>
<p>The competing substitution theory argues that formal regulations and corruption act as functional substitutes for navigating a market. This aligns with the “grease the wheels” hypothesis.</p>
<p>When regulatory quality is abysmal, corruption serves a vital functional purpose: it allows firms to bypass paralyzing bureaucratic delays. If a government aggressively controls corruption in this low-regulation environment, it actually harms investment by removing the only viable workaround. However, when regulatory quality is high, formal channels work perfectly. The “need” to pay bribes completely disappears. In this strong regulatory environment, corruption ceases to be a useful tool and instead becomes a purely punitive, unpredictable tax that exposes multinational firms to severe home-country legal liabilities, such as the U.S. Foreign Corrupt Practices Act. Because good regulations substitute for the “grease” of corruption, the marginal benefit of improving corruption control is actually lower when regulations are already high-functioning.</p>
<p>If substitution holds, the positive effect of controlling corruption on FDI will diminish as regulatory quality improves, because the high-quality regulations are already doing the heavy lifting to attract investors.</p>
<blockquote>
<p><strong>H1b (Substitution):</strong> The positive association between corruption control and FDI inflows will be weaker in countries with higher regulatory quality, resulting in a negative interaction coefficient (<span class="math inline">\(\hat{\beta}_3 &lt; 0\)</span>).</p>
</blockquote>
</section>
<section id="falsifiability-and-placebo-testing" class="level3" data-number="2.3">
<h3 data-number="2.3"><span class="header-section-number">2.3</span> Falsifiability and Placebo Testing</h3>
<p>Testing H1a against H1b makes this research design explicitly falsifiable. The empirical results will demonstrate which mechanism dominates the African context. Furthermore, to demonstrate that this moderating effect is driven solely by market regulations and not merely a generic byproduct of “good governance”, this study introduces a placebo test. If the interaction is truly about the operational mechanics of regulatory quality, then interacting corruption with a non-market governance dimension, such as Voice and Accountability, should yield a significantly weaker or statistically insignificant interaction term.</p>
</section>
</section>
<section id="research-design" class="level2" data-number="3">
<h2 data-number="3"><span class="header-section-number">3</span> Research Design</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1"><span class="header-section-number">3.1</span> Data</h3>
<p>This analysis draws on two World Bank datasets merged into a balanced country-year panel covering 54 African countries over the period 2005–2022, yielding complete country-year observations across all regression variables.</p>
<p>The outcome variable, <strong>FDI net inflows as a percentage of GDP</strong>, comes from the World Development Indicators (WDI). Expressing FDI as a share of GDP normalizes for country size, making comparisons across the continent’s highly heterogeneous economies meaningful. The two key institutional variables, <strong>Control of Corruption</strong> and <strong>Regulatory Quality</strong>, come from the Worldwide Governance Indicators (WGI), produced annually by the World Bank. Both are rescaled to run from approximately 0 (weakest governance) to 100 (strongest governance), so that higher values unambiguously indicate better institutions. The WGI draws on perception surveys of households, firms, and country experts, which introduces measurement error but offers the most consistent and comprehensive cross-country institutional data available for this time period.</p>
<p>Four covariates are included to control for confounders: <strong>natural resource rents (% of GDP)</strong>, which captures the resource-driven FDI common in Africa; <strong>trade openness (% of GDP)</strong>, which proxies for market integration; <strong>political stability</strong>, which controls for conflict and unrest; and <strong>GDP per capita</strong>, which accounts for market size and development level. All covariates are sourced from the WDI.</p>
<p>Table 1 presents summary statistics for the full analytical sample.</p>
<div id="tbl-summary" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 1: Summary Statistics — African Country-Year Panel, 2005–2022
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<colgroup>
<col style="width: 46%" />
<col style="width: 6%" />
<col style="width: 11%" />
<col style="width: 11%" />
<col style="width: 10%" />
<col style="width: 13%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FDI Net Inflows (% of GDP)</td>
<td style="text-align: right;">938</td>
<td style="text-align: right;">4.35</td>
<td style="text-align: right;">7.68</td>
<td style="text-align: right;">−17.29</td>
<td style="text-align: right;">103.34</td>
</tr>
<tr class="even">
<td>Regulatory Quality (WGI)</td>
<td style="text-align: right;">966</td>
<td style="text-align: right;">43.72</td>
<td style="text-align: right;">9.65</td>
<td style="text-align: right;">19.89</td>
<td style="text-align: right;">72.80</td>
</tr>
<tr class="odd">
<td>Control of Corruption (WGI)</td>
<td style="text-align: right;">967</td>
<td style="text-align: right;">34.83</td>
<td style="text-align: right;">12.86</td>
<td style="text-align: right;">9.68</td>
<td style="text-align: right;">71.55</td>
</tr>
<tr class="even">
<td>Voice and Accountability (WGI)</td>
<td style="text-align: right;">966</td>
<td style="text-align: right;">45.43</td>
<td style="text-align: right;">12.39</td>
<td style="text-align: right;">15.52</td>
<td style="text-align: right;">73.81</td>
</tr>
<tr class="odd">
<td>Natural Resource Rents (% of GDP)</td>
<td style="text-align: right;">891</td>
<td style="text-align: right;">11.83</td>
<td style="text-align: right;">11.61</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">66.06</td>
</tr>
<tr class="even">
<td>Trade Openness (% of GDP)</td>
<td style="text-align: right;">836</td>
<td style="text-align: right;">72.44</td>
<td style="text-align: right;">40.90</td>
<td style="text-align: right;">2.70</td>
<td style="text-align: right;">347.72</td>
</tr>
<tr class="odd">
<td>Political Stability (WGI)</td>
<td style="text-align: right;">966</td>
<td style="text-align: right;">55.19</td>
<td style="text-align: right;">14.86</td>
<td style="text-align: right;">13.76</td>
<td style="text-align: right;">87.83</td>
</tr>
<tr class="even">
<td>GDP per Capita (current US$)</td>
<td style="text-align: right;">951</td>
<td style="text-align: right;">2548.55</td>
<td style="text-align: right;">3153.11</td>
<td style="text-align: right;">147.23</td>
<td style="text-align: right;">19141.51</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Source: World Bank WDI and WGI. WGI scores range from approximately 0 (weakest) to 100 (strongest governance).</em> ### Regression Specification</p>
<p>To test H1a against H1b, we estimate the following two-way fixed effects model:</p>
<p><span class="math display">\[
\text{FDI}_{it} = \beta_0 + \beta_1 \text{Corruption}_{it} + \beta_2 \text{RegQuality}_{it} + \beta_3 (\text{Corruption}_{it} \times \text{RegQuality}_{it}) + \gamma \mathbf{X}_{it} + \alpha_i + \delta_t + \varepsilon_{it}
\]</span></p>
<p>where <span class="math inline">\(\alpha_i\)</span> are country fixed effects, <span class="math inline">\(\delta_t\)</span> are year fixed effects, and <span class="math inline">\(\mathbf{X}_{it}\)</span> is the vector of covariates described above. Standard errors are clustered by country to account for within-country serial correlation.</p>
<p>The coefficient of primary interest is <span class="math inline">\(\hat{\beta}_3\)</span>, the interaction term. A positive <span class="math inline">\(\hat{\beta}_3\)</span> supports H1a (complementarity); a negative <span class="math inline">\(\hat{\beta}_3\)</span> supports H1b (substitution). Note that <span class="math inline">\(\hat{\beta}_1\)</span> captures the association between corruption control and FDI when regulatory quality equals zero — the theoretical minimum of the WGI scale, not the sample mean (which is 43.72). Interpreting the main effect in isolation is therefore misleading; the marginal effects plot below provides the substantively meaningful picture.</p>
<p>Country fixed effects absorb all time-invariant country characteristics, such as geography, colonial history, and legal origins, that might jointly determine both governance and FDI. Year fixed effects absorb global shocks, such as the 2008 financial crisis and the COVID-19 pandemic, that affected FDI flows across continents.</p>
</section>
<section id="threats-to-inference" class="level3" data-number="3.2">
<h3 data-number="3.2"><span class="header-section-number">3.2</span> Threats to Inference</h3>
<p>The primary threat to a causal interpretation is <strong>reverse causality</strong>: countries that attract more FDI may use the resulting tax revenues to invest in better institutions, generating upward bias in the corruption and regulatory quality coefficients. A second concern is <strong>omitted variable bias</strong> due to time-varying confounders not captured by the covariates, such as regional trade agreements or country-specific political transitions.</p>
<p>Country fixed effects partially address both threats by removing confounding from stable country-level characteristics. However, time-varying omitted variables remain a concern, and the coefficients should therefore be interpreted as conditional associations rather than causal effects.</p>
</section>
</section>
<section id="findings" class="level2" data-number="4">
<h2 data-number="4"><span class="header-section-number">4</span> Findings</h2>
<p>Figure 1 provides a descriptive overview of the bivariate relationship between governance and FDI across African countries.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img src="FDI_Governance.png" class="img-fluid" /></p>
<figcaption>Figure 1: Scatter plots of country-level average FDI (% of GDP) against Control of Corruption (Panel A) and Regulatory Quality (Panel B), 2005–2022. Resource-rich countries (top quartile of natural resource rents) are shown as orange triangles. The weak positive correlations suggest that neither governance dimension has a simple unconditional relationship with FDI in Africa, motivating the conditional interaction analysis below. Source: World Bank WDI &amp; WGI.</figcaption>
</figure>
</div>
<p>The weak raw correlations in Figure 1 are consistent with neither governance dimension having a simple unconditional relationship with FDI across Africa. Resource-rich countries (orange triangles) are distributed across the full range of governance scores, suggesting that natural resource endowments do not systematically sort countries along either dimension. This motivates the interaction specification: governance may matter for FDI, but only under certain institutional conditions.</p>
<p>Figure 2 offers a first look at the interaction by splitting the sample at the median of regulatory quality (43.72). <img src="CoC.png" style="width:100.0%;height:200.0%" alt="Scatter plots of corruption control and FDI (% of GDP), split at the median of Regulatory Quality" /></p>
<p>The split-sample pattern in Figure 2 is instructive. Among countries with above-median regulatory quality, the relationship between corruption control and FDI is essentially flat — additional anti-corruption gains appear to deliver little marginal investment return where formal market institutions are already operative. Among countries with below-median regulatory quality, by contrast, corruption control is positively associated with FDI inflows, suggesting it functions as a partial substitute for the regulatory infrastructure those countries lack. This asymmetry constitutes preliminary visual support for H1b (substitution) over H1a (complementarity), and motivates the formal interaction test below.</p>
<p>The regression results are presented in Table 2, Column 1. The interaction coefficient β^3=−0.006_3 = -0.006 β^​3​=−0.006 (p&lt;0.05p &lt; 0.05 p&lt;0.05) provides clear support for H1b (substitution), allowing us to reject H1a (complementarity). To interpret this magnitude concretely, consider two countries at the 25th and 75th percentiles of Regulatory Quality — approximately 37 and 51 on the 0–100 scale. At the 25th percentile, a ten-point improvement in corruption control is associated with a 1.0 percentage point increase in FDI as a share of GDP (marginal effect ≈ 0.10). At the 75th percentile, the marginal effect is approximately zero and may turn slightly negative — consistent with Figure 3, where the point estimate crosses the zero line around a regulatory quality score of 48–50. Anti-corruption gains therefore deliver substantially smaller, and eventually negligible, investment returns in already well-regulated environments, a difference that is economically meaningful given that the sample mean FDI share is just 4.35% of GDP.</p>
<div id="tbl-regression" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 2: Main Model and Placebo Tests
</figcaption>
<div aria-describedby="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<colgroup>
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
<col style="width: 20%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Main Model</th>
<th style="text-align: center;">Placebo: Voice</th>
<th style="text-align: center;">Placebo: Lagged</th>
<th style="text-align: center;">Placebo: Portfolio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control of Corruption</td>
<td style="text-align: center;">0.323*</td>
<td style="text-align: center;">0.217</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.071</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.167)</td>
<td style="text-align: center;">(0.157)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.200)</td>
</tr>
<tr class="odd">
<td>Control of Corruption (t−1)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.493**</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.194)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Regulatory Quality</td>
<td style="text-align: center;">0.364*</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.111</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.184)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.217)</td>
</tr>
<tr class="odd">
<td>Regulatory Quality (t−1)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.368**</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.178)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Voice &amp; Accountability</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.007</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.130)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Corruption × Reg Quality</td>
<td style="text-align: center;">−0.006**</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.002</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.003)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.004)</td>
</tr>
<tr class="odd">
<td>Corruption × Voice &amp; Acct</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.003</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.003)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Corruption (t−1) × Reg Quality (t−1)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">−0.009**</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.004)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Resource Rents (% GDP)</td>
<td style="text-align: center;">−0.084*</td>
<td style="text-align: center;">−0.087**</td>
<td style="text-align: center;">−0.092**</td>
<td style="text-align: center;">−0.055</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.043)</td>
<td style="text-align: center;">(0.043)</td>
<td style="text-align: center;">(0.044)</td>
<td style="text-align: center;">(0.079)</td>
</tr>
<tr class="odd">
<td>Trade (% GDP)</td>
<td style="text-align: center;">0.105***</td>
<td style="text-align: center;">0.102***</td>
<td style="text-align: center;">0.110***</td>
<td style="text-align: center;">−0.017</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.031)</td>
<td style="text-align: center;">(0.031)</td>
<td style="text-align: center;">(0.031)</td>
<td style="text-align: center;">(0.011)</td>
</tr>
<tr class="odd">
<td>Political Stability</td>
<td style="text-align: center;">−0.039</td>
<td style="text-align: center;">−0.014</td>
<td style="text-align: center;">−0.021</td>
<td style="text-align: center;">−0.049</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.040)</td>
<td style="text-align: center;">(0.035)</td>
<td style="text-align: center;">(0.040)</td>
<td style="text-align: center;">(0.048)</td>
</tr>
<tr class="odd">
<td>GDP per Capita</td>
<td style="text-align: center;">−0.000***</td>
<td style="text-align: center;">−0.000***</td>
<td style="text-align: center;">−0.000***</td>
<td style="text-align: center;">−0.000</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
</tr>
<tr class="odd">
<td>Num. Obs.</td>
<td style="text-align: center;">774</td>
<td style="text-align: center;">774</td>
<td style="text-align: center;">731</td>
<td style="text-align: center;">431</td>
</tr>
<tr class="even">
<td>R²</td>
<td style="text-align: center;">0.497</td>
<td style="text-align: center;">0.495</td>
<td style="text-align: center;">0.516</td>
<td style="text-align: center;">0.225</td>
</tr>
<tr class="odd">
<td>R² Adj.</td>
<td style="text-align: center;">0.445</td>
<td style="text-align: center;">0.443</td>
<td style="text-align: center;">0.463</td>
<td style="text-align: center;">0.107</td>
</tr>
<tr class="even">
<td>FE: country</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓</td>
</tr>
<tr class="odd">
<td>FE: year</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓</td>
<td style="text-align: center;">✓</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>* p &lt; 0.1, ** p &lt; 0.05, *** p &lt; 0.01. Standard errors clustered by country in parentheses. Columns 1–3 use FDI (% GDP) as outcome; Column 4 uses portfolio equity (% GDP). To understand precisely where in the regulatory quality distribution the moderation effect is statistically operative, Figure 3 plots the marginal effect of corruption control on FDI across the full observed range of regulatory quality with 95% confidence intervals.</p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img src="Marginal_Effect.png" class="img-fluid" style="width:100.0%" /></p>
<figcaption>Figure 3: Marginal effect of corruption control (WGI) on FDI net inflows (% of GDP) across the observed range of Regulatory Quality, estimated from the two-way fixed effects interaction model.</figcaption>
</figure>
</div>
<p>Figure 3 reveals important heterogeneity in where the substitution effect is statistically and substantively operative. At low levels of regulatory quality (around 20 on the WGI scale), the marginal effect of corruption control is positive — approximately 0.20 percentage points of FDI per GDP per unit improvement — but is estimated with considerable imprecision, with confidence intervals spanning zero. In institutionally weak environments, corruption control neither reliably attracts nor deters FDI, likely because the entire formal investment framework is sufficiently underdeveloped that marginal anti-corruption signals are insufficient to shift investor behaviour. As regulatory quality rises toward and above the sample mean (43.7), the point estimate declines monotonically, crossing zero around a score of 48–50 and turning statistically significant and negative at higher values, where the confidence band lies entirely below the zero line. It is precisely in Africa’s better-governed economies — where investors are already operating through formal channels — that further anti-corruption progress is associated with reduced FDI inflows, plausibly because stricter enforcement removes informal flexibility without yet providing commensurate new formal assurances. Crucially, given that WGI indices are perception-based and therefore subject to classical measurement error, these estimates are likely attenuated toward zero, suggesting that the true substitution effect at high regulatory quality may be larger in magnitude than reported here.</p>
</section>
<section id="empirical-extension" class="level2" data-number="5">
<h2 data-number="5"><span class="header-section-number">5</span> Empirical Extension</h2>
<p>The main finding — that corruption control’s association with FDI diminishes and eventually turns negative as regulatory quality improves — could reflect two alternative explanations that must be ruled out before the substitution interpretation can be sustained. First, the negative interaction might be a generic “good governance” effect, in which any pairing of institutional dimensions produces a similar moderating pattern simply because governance indices are correlated with one another. Second, the effect might be an artefact of the FDI measure itself: long-horizon foreign direct investment requires firms to physically embed in a host economy, navigating permits, contracts, and local workforces, and so may be uniquely sensitive to the regulatory–corruption nexus in ways that short-horizon financial flows are not.</p>
<p><strong>Placebo 1: Non-market governance (Voice and Accountability).</strong> Column 2 replaces Regulatory Quality with the WGI Voice and Accountability index, which captures political freedoms, civil liberties, and press freedom. Critically, this dimension has no direct bearing on permit issuance, contract enforcement, or market entry — the precise channels through which the substitution mechanism operates. The flat slope in Figure 2’s above-median panel, and the zero-crossing in Figure 3, both implicate <em>market-operational</em> institutions specifically: environments where formal rules govern the day-to-day transaction costs of doing business. Voice and Accountability does not govern these transactions. If the Figure 3 pattern were simply a reflection of correlated governance indices rather than a specific institutional mechanism, the interaction with Voice and Accountability should be similarly signed and significant. It is not: the coefficient is −0.003 and statistically insignificant (p&gt;0.1), approximately half the magnitude of the main interaction and indistinguishable from zero. This rules out a generic governance halo interpretation and anchors the finding to the market-operational channel.</p>
<p><strong>Placebo 2: Portfolio equity flows.</strong> Column 4 replaces the dependent variable with portfolio equity inflows (% of GDP). Unlike FDI, portfolio investment involves the acquisition of listed financial assets rather than operational assets; portfolio investors do not build facilities, hire local management, or repeatedly engage with regulatory agencies. They are therefore largely insulated from the informal flexibility that the substitution mechanism posits: the progressive removal of that flexibility as regulatory quality improves — visible in Figure 3’s declining marginal effect — should not register in their investment calculus. Consistent with this prediction, the interaction coefficient for portfolio flows is -0.002 and statistically insignificant, confirming that the pattern documented in Figures 2 and 3 is specific to investment modes that require sustained regulatory engagement. Together, these tests triangulate the finding with precision: the substitution effect identified in Figure 3 is specific to a market-operational governance dimension rather than institutional quality in general, and to long-horizon investment rather than financial flows — exactly the combination the proposed mechanism requires. The placebo results also provide indirect reassurance that the correlated structure of WGI indices is not mechanically generating the main result.</p>
<p><strong>Lagged specification.</strong> Column 3 re-estimates the main model with one-year lags on both governance variables. The sign, magnitude, and significance of the interaction term are nearly identical to those in Column 1, unsurprising given the high year-to-year persistence of WGI scores, which change slowly by design. The lagged model therefore largely reproduces the main result with a one-year offset rather than providing genuinely independent evidence. It is retained for completeness, but the two placebo tests, which vary the governance dimension and the outcome variable rather than timing, are the more informative robustness checks.</p>
</section>
<section id="discussion-and-policy-implications" class="level2" data-number="6">
<h2 data-number="6"><span class="header-section-number">6</span> Discussion and Policy Implications</h2>
<p>This analysis finds consistent support for the substitution mechanism (H1b). In the African context, regulatory quality and corruption control function as institutional substitutes: as formal market institutions strengthen, the marginal investment return to anti-corruption progress declines, eventually turning negative among the continent’s better-governed economies. Rather than resolving the “grease the wheels” versus “sand the wheels” debate unconditionally, the results suggest the answer is context-dependent — corruption control sands the wheels most where formal wheels already turn smoothly. The two-way fixed effects design, lagged specification, and placebo tests collectively make it difficult to attribute this pattern to generic governance quality or short-horizon financial dynamics. Nevertheless, time-varying omitted variables cannot be ruled out, and the WGI’s perception-based construction introduces classical measurement error that likely attenuates estimates toward zero — meaning the true substitution effect is probably larger than reported here. Results should be read as conservative conditional associations rather than clean causal identification. The policy implications map directly onto the three regimes visible in Figure 3. For weak-regulatory states such as Chad or the Central African Republic, anti-corruption enforcement in isolation will not move investors; the priority is foundational regulatory infrastructure. For transition-zone economies around the sample mean, such as Kenya, Senegal, Tanzania coordinated reform is warranted: regulatory deepening and anti-corruption enforcement should advance together so that firms exiting informal channels find functioning formal alternatives. For better-governed economies such as Botswana, Mauritius, or Rwanda, the finding carries a counterintuitive warning: aggressive enforcement is associated with lower FDI, likely because investors lose informal flexibility before formal assurances materialise. Sequencing matters here, enforcement should be paired with explicit strengthening of investor protections and regulatory predictability. Future research should pursue cleaner identification through historical institutional instruments or quasi-experimental shocks such as FATF grey-listing, and firm-level data to trace the mechanism to individual investment decisions.</p>
<hr />
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-benassy2007" class="csl-entry" role="listitem">
Bénassy-Quéré, Agnès, Maylis Coupet, and Thierry Mayer. 2007. <span>“Institutional Determinants of Foreign Direct Investment.”</span> <em>The World Economy</em> 30 (5): 764–82. <a href="https://doi.org/10.1111/j.1467-9701.2007.01022.x">https://doi.org/10.1111/j.1467-9701.2007.01022.x</a>.
</div>
<div id="ref-lakha2024" class="csl-entry" role="listitem">
Lakha, Bhavna, Adeola Oyenubi, David Fadiran, and Nihaal Naik. 2024. <span>“Governance and the Relationship Between Corruption and <span>FDI</span> in <span>Africa</span>: A Threshold Regression Analysis.”</span> <em>International Review of Applied Economics</em> 38 (6): 613–32. <a href="https://doi.org/10.1080/02692171.2024.2382112">https://doi.org/10.1080/02692171.2024.2382112</a>.
</div>
<div id="ref-mauro1995" class="csl-entry" role="listitem">
Mauro, Paolo. 1995. <span>“Corruption and Growth.”</span> <em>The Quarterly Journal of Economics</em> 110 (3): 681–712. <a href="https://doi.org/10.2307/2946696">https://doi.org/10.2307/2946696</a>.
</div>
<div id="ref-meon2005" class="csl-entry" role="listitem">
Méon, Pierre-Guillaume, and Khalid Sekkat. 2005. <span>“Does Corruption Grease or Sand the Wheels of Growth?”</span> <em>Public Choice</em> 122 (1–2): 69–97. <a href="https://doi.org/10.1007/s11127-005-3988-0">https://doi.org/10.1007/s11127-005-3988-0</a>.
</div>
<div id="ref-quazi2014" class="csl-entry" role="listitem">
Quazi, Rahim, Vijay Vemuri, and Mohamed Soliman. 2014. <span>“Impact of Corruption on Foreign Direct Investment in <span>Africa</span>.”</span> <em>International Business Research</em> 7 (4): 1–10. <a href="https://doi.org/10.5539/ibr.v7n4p1">https://doi.org/10.5539/ibr.v7n4p1</a>.
</div>
<div id="ref-unctad2026" class="csl-entry" role="listitem">
United Nations Conference on Trade and Development. 2026. <span>“Global Investment Trends Monitor, No. 50: Global <span>FDI</span> up 14% in 2025.”</span> UNCTAD/DIAE/IA/INF/2026/1. UNCTAD. <a href="https://unctad.org/publication/global-investment-trends-monitor-no-50">https://unctad.org/publication/global-investment-trends-monitor-no-50</a>.
</div>
<div id="ref-wei2000" class="csl-entry" role="listitem">
Wei, Shang-Jin. 2000. <span>“How Taxing Is Corruption on International Investors?”</span> <em>The Review of Economics and Statistics</em> 82 (1): 1–11. <a href="https://doi.org/10.1162/003465300558533">https://doi.org/10.1162/003465300558533</a>.
</div>
</div>
<div id="quarto-navigation-envelope" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1zaWRlYmFyLXRpdGxl">Razi Mrad - PSCI 3200</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXItdGl0bGU=">Razi Mrad - PSCI 3200</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6SG9tZQ==">Home</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L2luZGV4Lmh0bWw=">/index.html</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6RmluYWwgUHJvamVjdA==">Final Project</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLWludC1uYXZiYXI6L3BzY2lfZmluYWwuaHRtbA==">/psci_final.html</span></p>
</div>
<div id="quarto-meta-markdown" class="hidden">
<p><span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGF0aXRsZQ==">Grease or Sand? Regulatory Quality as a Moderator of Corruption’s Effect on FDI in Africa – Razi Mrad - PSCI 3200</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkdGl0bGU=">Grease or Sand? Regulatory Quality as a Moderator of Corruption’s Effect on FDI in Africa – Razi Mrad - PSCI 3200</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZHRpdGxl">Grease or Sand? Regulatory Quality as a Moderator of Corruption’s Effect on FDI in Africa – Razi Mrad - PSCI 3200</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW1ldGFzaXRlbmFtZQ==">Razi Mrad - PSCI 3200</span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLXR3aXR0ZXJjYXJkZGVzYw=="></span> <span class="hidden quarto-markdown-envelope-contents" data-render-id="cXVhcnRvLW9nY2FyZGRkZXNj"></span></p>
</div>
</section>

</main> <!-- /main -->
<script id = "quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->

</body>

</html>
